-- Export logs table — tracks every data export generated by admin/principal

create table if not exists public.export_logs (
  id           uuid        primary key default gen_random_uuid(),
  school_id    text        not null,
  category     text        not null,   -- students | staff | attendance | fees
  format       text        not null,   -- pdf | excel
  label        text        not null,
  row_count    integer     not null default 0,
  exported_by  text        not null,
  exported_at  timestamptz not null default now()
);

create index if not exists export_logs_school_id_idx on public.export_logs (school_id, exported_at desc);

alter table public.export_logs enable row level security;

create policy "Admin can manage export logs"
  on public.export_logs
  for all
  using (
    exists (
      select 1 from public.profiles
      where id = auth.uid()
        and school_id = export_logs.school_id
        and role in ('admin', 'principal')
    )
  )
  with check (
    exists (
      select 1 from public.profiles
      where id = auth.uid()
        and school_id = export_logs.school_id
        and role in ('admin', 'principal')
    )
  );
