import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { getProgressLevelDetails, SKILL_LEVELS, type Skill } from '../constants/progressSkills';

const NAVY = '#1E3A5F';
const GOLD = '#DAA520';

export interface ReportStudent {
  id: string;
  full_name: string;
  roll_number: string | null;
  skills: Skill[];
  overallPct: number;
}

function levelColor(pct: number) {
  const lvl = SKILL_LEVELS.reduce((prev, curr) =>
    Math.abs(curr.progress - pct) < Math.abs(prev.progress - pct) ? curr : prev
  );
  return lvl.color;
}

function levelLabel(pct: number) {
  const lvl = SKILL_LEVELS.reduce((prev, curr) =>
    Math.abs(curr.progress - pct) < Math.abs(prev.progress - pct) ? curr : prev
  );
  return lvl.label;
}

const baseStyles = `
  * { box-sizing: border-box; margin: 0; padding: 0; font-family: -apple-system, 'Segoe UI', Roboto, sans-serif; }
  body { color: ${NAVY}; padding: 32px; }
  .header { display: flex; align-items: center; justify-content: space-between;
    border-bottom: 3px solid ${GOLD}; padding-bottom: 16px; margin-bottom: 24px; }
  .logo { font-size: 22px; font-weight: 900; color: ${NAVY}; }
  .logo span { color: ${GOLD}; }
  .meta { text-align: right; font-size: 12px; color: #5A6C7D; }
  h1 { font-size: 20px; margin-bottom: 4px; }
  .pill { display: inline-block; padding: 4px 12px; border-radius: 20px;
    font-size: 12px; font-weight: 700; color: #fff; }
  .bar { height: 9px; background: #EEF2F7; border-radius: 5px; overflow: hidden; margin-top: 5px; }
  .bar > div { height: 9px; border-radius: 5px; }
  table { width: 100%; border-collapse: collapse; margin-top: 12px; }
  th { text-align: left; font-size: 11px; text-transform: uppercase; letter-spacing: .5px;
    color: #8B95A1; padding: 8px 6px; border-bottom: 2px solid #EEF2F7; }
  td { padding: 10px 6px; border-bottom: 1px solid #F0F4F8; font-size: 13px; vertical-align: middle; }
  .footer { margin-top: 32px; padding-top: 14px; border-top: 1px solid #EEF2F7;
    font-size: 10px; color: #8B95A1; text-align: center; }
  .skill-name { font-weight: 600; }
  .emoji { font-size: 15px; margin-right: 6px; }
`;

function reportHeader(subtitle: string) {
  const today = new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' });
  return `
    <div class="header">
      <div>
        <div class="logo">DAM <span>PreSchool</span></div>
        <div style="font-size:12px;color:#5A6C7D;margin-top:2px;">${subtitle}</div>
      </div>
      <div class="meta">Generated<br/><strong>${today}</strong></div>
    </div>`;
}

const footer = `<div class="footer">DAM PreSchool · Confidential Progress Report · Generated by the School Management App</div>`;

/** Export a single student's progress report */
export async function exportStudentReport(
  student: ReportStudent,
  term: number,
  className: string
): Promise<void> {
  const rows = student.skills
    .map((sk) => {
      const ld = getProgressLevelDetails(sk.level);
      return `
        <tr>
          <td><span class="emoji">${sk.emoji}</span><span class="skill-name">${sk.name}</span>
            ${sk.required ? `<span style="color:${GOLD};font-size:10px;"> ★</span>` : ''}</td>
          <td style="width:42%;">
            <div class="bar"><div style="width:${ld.progress}%;background:${ld.color};"></div></div>
          </td>
          <td style="text-align:right;width:110px;">
            <span class="pill" style="background:${ld.color};">${ld.label}</span>
          </td>
        </tr>`;
    })
    .join('');

  const html = `
    <html><head><style>${baseStyles}</style></head><body>
      ${reportHeader(`Student Progress Report · Term ${term}`)}
      <h1>${student.full_name}</h1>
      <div style="font-size:13px;color:#5A6C7D;margin-bottom:18px;">
        Class: <strong>${className}</strong>${student.roll_number ? ` · Roll #${student.roll_number}` : ''}
      </div>
      <div style="display:flex;align-items:center;gap:16px;background:#F8FAFC;border-radius:14px;padding:18px;margin-bottom:8px;">
        <div style="font-size:40px;font-weight:900;color:${levelColor(student.overallPct)};">${student.overallPct}%</div>
        <div>
          <div style="font-size:12px;color:#8B95A1;">Overall Progress</div>
          <span class="pill" style="background:${levelColor(student.overallPct)};margin-top:4px;">${levelLabel(student.overallPct)}</span>
        </div>
      </div>
      <table>
        <thead><tr><th>Skill</th><th>Progress</th><th style="text-align:right;">Level</th></tr></thead>
        <tbody>${rows}</tbody>
      </table>
      ${footer}
    </body></html>`;

  await printAndShare(html);
}

/** Export a whole class summary report */
export async function exportClassReport(
  className: string,
  classFullName: string,
  term: number,
  students: ReportStudent[],
  skillAverages: { name: string; emoji: string; avgPct: number; required: boolean }[]
): Promise<void> {
  const classAvg = students.length
    ? Math.round(students.reduce((s, st) => s + st.overallPct, 0) / students.length)
    : 0;

  const studentRows = [...students]
    .sort((a, b) => b.overallPct - a.overallPct)
    .map((st, i) => `
      <tr>
        <td style="color:#8B95A1;width:30px;">${i + 1}</td>
        <td><strong>${st.full_name}</strong>${st.roll_number ? `<span style="color:#8B95A1;font-size:11px;"> · #${st.roll_number}</span>` : ''}</td>
        <td style="width:35%;"><div class="bar"><div style="width:${st.overallPct}%;background:${levelColor(st.overallPct)};"></div></div></td>
        <td style="text-align:right;width:60px;font-weight:800;color:${levelColor(st.overallPct)};">${st.overallPct}%</td>
        <td style="text-align:right;width:100px;"><span class="pill" style="background:${levelColor(st.overallPct)};">${levelLabel(st.overallPct)}</span></td>
      </tr>`)
    .join('');

  const skillRows = skillAverages
    .map((sk) => `
      <tr>
        <td><span class="emoji">${sk.emoji}</span>${sk.name}${sk.required ? `<span style="color:${GOLD};"> ★</span>` : ''}</td>
        <td style="width:45%;"><div class="bar"><div style="width:${sk.avgPct}%;background:${levelColor(sk.avgPct)};"></div></div></td>
        <td style="text-align:right;width:60px;font-weight:800;color:${levelColor(sk.avgPct)};">${sk.avgPct}%</td>
      </tr>`)
    .join('');

  const html = `
    <html><head><style>${baseStyles}</style></head><body>
      ${reportHeader(`Class Progress Report · Term ${term}`)}
      <h1>${classFullName} <span style="color:#8B95A1;font-size:15px;">(${className})</span></h1>
      <div style="display:flex;gap:12px;margin:16px 0;">
        <div style="flex:1;background:#F8FAFC;border-radius:12px;padding:14px;text-align:center;">
          <div style="font-size:26px;font-weight:900;color:${NAVY};">${students.length}</div>
          <div style="font-size:11px;color:#8B95A1;">Students</div>
        </div>
        <div style="flex:1;background:#F8FAFC;border-radius:12px;padding:14px;text-align:center;">
          <div style="font-size:26px;font-weight:900;color:${levelColor(classAvg)};">${classAvg}%</div>
          <div style="font-size:11px;color:#8B95A1;">Class Average</div>
        </div>
      </div>
      <h2 style="font-size:14px;margin:20px 0 4px;">Student Rankings</h2>
      <table><thead><tr><th>#</th><th>Student</th><th>Progress</th><th></th><th></th></tr></thead>
        <tbody>${studentRows || '<tr><td colspan="5" style="text-align:center;color:#8B95A1;padding:20px;">No students enrolled</td></tr>'}</tbody></table>
      <h2 style="font-size:14px;margin:24px 0 4px;">Skill Averages</h2>
      <table><thead><tr><th>Skill</th><th>Class Average</th><th></th></tr></thead>
        <tbody>${skillRows}</tbody></table>
      ${footer}
    </body></html>`;

  await printAndShare(html);
}

async function printAndShare(html: string) {
  const { uri } = await Print.printToFileAsync({ html });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: 'Share Progress Report' });
  }
}
